import React from 'react';
import { Link } from 'react-router-dom';
import { FaRobot, FaLightbulb, FaCode, FaUsers, FaArrowRight } from 'react-icons/fa';
import useAuthStore from '../stores/authStore';

function Home() {
  const { isAuthenticated } = useAuthStore();

  return (
    <div className="bg-gradient-to-b from-blue-50 to-white">
      {/* Hero Section */}
      <section className="container py-20 text-center">
        <div className="mb-8">
          <FaRobot className="text-6xl text-primary mx-auto mb-4" />
        </div>
        <h1 className="text-5xl md:text-6xl font-bold mb-4">
          AI Project Idea Generator for Students
        </h1>
        <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
          Generate unique, AI-powered project ideas tailored to your skills, interests, and academic level. Perfect for B.Tech students!
        </p>
        <div className="flex gap-4 justify-center flex-wrap">
          {isAuthenticated ? (
            <>
              <Link to="/generate" className="btn btn-primary flex items-center gap-2">
                <FaRobot /> Start Generating <FaArrowRight />
              </Link>
              <Link to="/dashboard" className="btn btn-outline">
                Go to Dashboard
              </Link>
            </>
          ) : (
            <>
              <Link to="/register" className="btn btn-primary flex items-center gap-2">
                <FaRobot /> Get Started <FaArrowRight />
              </Link>
              <Link to="/login" className="btn btn-outline">
                Login
              </Link>
            </>
          )}
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-white py-20">
        <div className="container">
          <h2 className="text-4xl font-bold text-center mb-12">Key Features</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="card text-center">
              <FaLightbulb className="text-4xl text-primary mx-auto mb-4" />
              <h3 className="text-xl font-bold mb-2">AI-Powered Ideas</h3>
              <p className="text-gray-600">
                Get unique project ideas generated by advanced AI algorithms tailored to your profile
              </p>
            </div>
            <div className="card text-center">
              <FaCode className="text-4xl text-primary mx-auto mb-4" />
              <h3 className="text-xl font-bold mb-2">Complete Tech Stack</h3>
              <p className="text-gray-600">
                Each project includes detailed tech stack, architecture, and implementation roadmap
              </p>
            </div>
            <div className="card text-center">
              <FaUsers className="text-4xl text-primary mx-auto mb-4" />
              <h3 className="text-xl font-bold mb-2">Personalized</h3>
              <p className="text-gray-600">
                Customize ideas based on difficulty level, duration, team size, and your interests
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* How It Works Section */}
      <section className="container py-20">
        <h2 className="text-4xl font-bold text-center mb-12">How It Works</h2>
        <div className="grid md:grid-cols-4 gap-8">
          {[
            { step: '1', title: 'Sign Up', desc: 'Create your account in seconds' },
            { step: '2', title: 'Profile', desc: 'Tell us about your skills and interests' },
            { step: '3', title: 'Generate', desc: 'Get AI-powered project ideas' },
            { step: '4', title: 'Build', desc: 'Start building your perfect project' },
          ].map((item) => (
            <div key={item.step} className="text-center">
              <div className="w-12 h-12 bg-primary text-white rounded-full flex items-center justify-center text-xl font-bold mx-auto mb-4">
                {item.step}
              </div>
              <h3 className="text-lg font-bold mb-2">{item.title}</h3>
              <p className="text-gray-600">{item.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA Section */}
      <section className="gradient-bg text-white py-20">
        <div className="container text-center">
          <h2 className="text-4xl font-bold mb-4">Ready to Generate Your Project Ideas?</h2>
          <p className="text-xl mb-8 text-blue-100">Join hundreds of students using ProjectGen AI to find their perfect project</p>
          {!isAuthenticated && (
            <Link to="/register" className="btn bg-white text-primary hover:bg-gray-100 inline-block">
              Start Now
            </Link>
          )}
        </div>
      </section>
    </div>
  );
}

export default Home;
